### ISSUE TITLE
Only outputs once with local models

### ISSUE THREAD

**Issue by renatokuipers** [ItzCrazyKns/Not-Devin#3]
I added local support by simply adding OPENAI_BASE_URL to the .env file.

while this works and it inferences the local model, it outputs only 1 output and then stops the script.

Is this something you are still working on? Is this something that has to do with Function calling? (Which shouldn't matter since I have a function calling local LLM called "Llama 2 chat hf function calling V2 7B Q4_K_M gguf" which is perfectly able to call functions..)

I tested with 6 different local models, but each time after 1 result, the program just stops..

**Comment by ItzCrazyKns** [comment]
Hi mate, I planned to add support for local models but someone already made a better version of Not Devin that has access to the internet as well, which you can see [here](https://github.com/stitionai/devika). With this you can use local LLMs by using [Ollama](https://github.com/ollama/ollama),
